apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.service.ports.grpc }}
      targetPort: {{ .Values.service.ports.grpc }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.ports.pgrpc }}
      targetPort: {{ .Values.service.ports.pgrpc }}
      protocol: TCP
      name: pgrpc
  selector:
    app: {{ .Chart.Name }}
