replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/streams
  tag: latest
  pullPolicy: Always
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

service:
  ports:
    grpc: 5002
    pgrpc: 5102

resources:
  limits:
   cpu: 1000m
   memory: 512Mi
  requests:
   cpu: 1000m
   memory: 512Mi

autoscaler:
  minCount: 1
  maxCount: 3
  targets:
    targetCPUUtilizationPercentage: 70

config:
  USERS_RPC_ADDR: "users.console.svc.cluster.local:5000"
  ACCOUNTS_RPC_ADDR: "accounts.console.svc.cluster.local:5001"
  EMITTER_RPC_ADDR: "emitter.console.svc.cluster.local:5003"
  BILLING_RPC_ADDR: "billing.console.svc.cluster.local:5120"

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-streams"
  vault.hashicorp.com/agent-inject-secret-common: "videocoin/v1/networks/everest-dev/console/common"
  vault.hashicorp.com/agent-inject-secret-config: "videocoin/v1/networks/everest-dev/console/streams"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/common" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/streams" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
