replicasCount: 1
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/streams
  tag: latest
  pullPolicy: Always

config: {}

service:
  type: ClusterIP
  externalRpcPort: 5002
  internalRpcPort: 5002
  externalPrivateRpcPort: 5102
  internalPrivateRpcPort: 5102

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

secrets:
  dbUri: ""
  mqUri: ""
  secret: ""
  sentryDsn: ""
